package com.med.slot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DoctorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAllPropertiesEquals(Doctor expected, Doctor actual) {
        assertDoctorAutoGeneratedPropertiesEquals(expected, actual);
        assertDoctorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAllUpdatablePropertiesEquals(Doctor expected, Doctor actual) {
        assertDoctorUpdatableFieldsEquals(expected, actual);
        assertDoctorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorAutoGeneratedPropertiesEquals(Doctor expected, Doctor actual) {
        assertThat(actual)
            .as("Verify Doctor auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorUpdatableFieldsEquals(Doctor expected, Doctor actual) {
        assertThat(actual)
            .as("Verify Doctor relevant properties")
            .satisfies(a -> assertThat(a.getSpecialty()).as("check specialty").isEqualTo(expected.getSpecialty()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorUpdatableRelationshipsEquals(Doctor expected, Doctor actual) {
        assertThat(actual)
            .as("Verify Doctor relationships")
            .satisfies(a -> assertThat(a.getClinic()).as("check clinic").isEqualTo(expected.getClinic()));
    }
}
