package com.med.slot.domain;

import static com.med.slot.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class DoctorScheduleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorScheduleAllPropertiesEquals(DoctorSchedule expected, DoctorSchedule actual) {
        assertDoctorScheduleAutoGeneratedPropertiesEquals(expected, actual);
        assertDoctorScheduleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorScheduleAllUpdatablePropertiesEquals(DoctorSchedule expected, DoctorSchedule actual) {
        assertDoctorScheduleUpdatableFieldsEquals(expected, actual);
        assertDoctorScheduleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorScheduleAutoGeneratedPropertiesEquals(DoctorSchedule expected, DoctorSchedule actual) {
        assertThat(actual)
            .as("Verify DoctorSchedule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorScheduleUpdatableFieldsEquals(DoctorSchedule expected, DoctorSchedule actual) {
        assertThat(actual)
            .as("Verify DoctorSchedule relevant properties")
            .satisfies(a -> assertThat(a.getDayOfWeek()).as("check dayOfWeek").isEqualTo(expected.getDayOfWeek()))
            .satisfies(a ->
                assertThat(a.getStartTime())
                    .as("check startTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getStartTime())
            )
            .satisfies(a ->
                assertThat(a.getEndTime()).as("check endTime").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getEndTime())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDoctorScheduleUpdatableRelationshipsEquals(DoctorSchedule expected, DoctorSchedule actual) {
        assertThat(actual)
            .as("Verify DoctorSchedule relationships")
            .satisfies(a -> assertThat(a.getDoctor()).as("check doctor").isEqualTo(expected.getDoctor()));
    }
}
