package com.med.slot.domain;

import static com.med.slot.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class SmsNotificationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmsNotificationAllPropertiesEquals(SmsNotification expected, SmsNotification actual) {
        assertSmsNotificationAutoGeneratedPropertiesEquals(expected, actual);
        assertSmsNotificationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmsNotificationAllUpdatablePropertiesEquals(SmsNotification expected, SmsNotification actual) {
        assertSmsNotificationUpdatableFieldsEquals(expected, actual);
        assertSmsNotificationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmsNotificationAutoGeneratedPropertiesEquals(SmsNotification expected, SmsNotification actual) {
        assertThat(actual)
            .as("Verify SmsNotification auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmsNotificationUpdatableFieldsEquals(SmsNotification expected, SmsNotification actual) {
        assertThat(actual)
            .as("Verify SmsNotification relevant properties")
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getMessage()).as("check message").isEqualTo(expected.getMessage()))
            .satisfies(a ->
                assertThat(a.getSendAt()).as("check sendAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getSendAt())
            )
            .satisfies(a ->
                assertThat(a.getSentAt()).as("check sentAt").usingComparator(zonedDataTimeSameInstant).isEqualTo(expected.getSentAt())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getErrorMessage()).as("check errorMessage").isEqualTo(expected.getErrorMessage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSmsNotificationUpdatableRelationshipsEquals(SmsNotification expected, SmsNotification actual) {
        assertThat(actual)
            .as("Verify SmsNotification relationships")
            .satisfies(a -> assertThat(a.getClinic()).as("check clinic").isEqualTo(expected.getClinic()))
            .satisfies(a -> assertThat(a.getAppointment()).as("check appointment").isEqualTo(expected.getAppointment()));
    }
}
